# Generated by Django 3.1.7 on 2021-03-20 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=datetime.datetime(2021, 3, 20, 12, 43, 59, 840687, tzinfo=utc))),
                ('deadline', models.DateField()),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
